[package]
name = "demo"
version = "0.1.0"
description = "Hardcore's examples."
edition = "2021"
authors = ["Pedro Valente <pedro.amaral.valente@gmail.com>"]
repository = "https://github.com/StrengthDev/hardcore-engine"
license-file = "../LICENSE"
publish = false

[dependencies]
